app:
    resource: "@AppBundle/Controller/"
    type:     annotation

register:
    path: /
    defaults: { _controller: AppBundle:Registration:register}

login:
    path: /login
    defaults: { _controller: AppBundle:Security:login}

logout:
    path: /logout

schedule:
    path: /schedule
    defaults: { _controller: AppBundle:Schedule:schedule}