# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost:      12

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        my_entity_provider:
            entity:
                class:              AppBundle:User
                property:           username
                manager_name:       ~

    firewalls:
        main:
            pattern: ^/
            form_login:
                login_path: login
                check_path: login
                default_target_path: schedule
                always_use_default_target_path: false
                post_only: true

            logout:
                path: /logout
                target: /

            anonymous:    true

    access_control:
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/schedule$, role: ROLE_USER }
        - { path: ^/admin$, role: ROLE_ADMIN }
